/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "on-tertiary-fixed": "#243155",
              "on-primary-fixed-variant": "#255c74",
              "outline": "#777b7c",
              "on-surface-variant": "#5b6061",
              "inverse-primary": "#ade1fe",
              "tertiary-container": "#c1cdfb",
              "inverse-surface": "#0c0f0f",
              "tertiary-fixed": "#c1cdfb",
              "error-container": "#fa746f",
              "on-tertiary-container": "#38446a",
              "on-secondary-fixed-variant": "#605d34",
              "on-tertiary-fixed-variant": "#414d73",
              "primary-fixed-dim": "#9fd3f0",
              "surface-tint": "#EAB308",
              "surface": "#FFFDF5",
              "on-error-container": "#6e0a12",
              "secondary-container": "#FEF9C3",
              "inverse-on-surface": "#9c9d9d",
              "tertiary-fixed-dim": "#b3c0ec",
              "on-tertiary": "#f9f8ff",
              "secondary-dim": "#57542d",
              "tertiary-dim": "#455278",
              "on-primary": "#422006",
              "primary-dim": "#A16207",
              "secondary": "#713F12",
              "tertiary": "#1E3A8A",
              "on-secondary-fixed": "#422006",
              "surface-variant": "#FDE68A",
              "surface-container-low": "#FEFCE8",
              "surface-container-high": "#FEF9C3",
              "on-secondary-container": "#713F12",
              "background": "#FFFDF5",
              "on-secondary": "#422006",
              "secondary-fixed": "#FEF08A",
              "on-primary-container": "#451a03",
              "surface-bright": "#FFFDF5",
              "error-dim": "#67040d",
              "secondary-fixed-dim": "#FDE68A",
              "outline-variant": "#EAB308",
              "surface-container": "#FEF08A",
              "on-error": "#fff7f6",
              "primary": "#CA8A04",
              "primary-fixed": "#FEF9C3",
              "on-background": "#422006",
              "surface-container-lowest": "#ffffff",
              "surface-container-highest": "#FDE68A",
              "surface-dim": "#FEF08A",
              "on-surface": "#422006",
              "error": "#a83836",
              "on-primary-fixed": "#451a03",
              "primary-container": "#FEF9C3"
      },
      "borderRadius": {
              "DEFAULT": "1rem",
              "lg": "2rem",
              "xl": "3rem",
              "full": "9999px"
      },
      "fontFamily": {
              "headline": ["Plus Jakarta Sans"],
              "body": ["Be Vietnam Pro"],
              "label": ["Plus Jakarta Sans"]
      }
    },
  },
  plugins: [],
}
